<div id="banner">
    <img src='<?php echo $this->getViewFileUrl('images/banner-livros-venda.png'); ?>' alt="error" ">
</div>

<div><br/></div>

<div id="Books">
    <h2><b>&nbsp;&nbsp;Livros</b></h2>
    <img class="catalogo" src='<?php echo $this->getViewFileUrl('images/Book.jpg'); ?>' alt="error" ">

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/livros/id/24/">
        <img class="books" src='<?php echo $this->getViewFileUrl('images/livro_acao.jpg'); ?>' alt="error"
            title="Ação" ">
    </a>

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/livros/id/26/">
        <img class="books" src='<?php echo $this->getViewFileUrl('images/livro_aventura.jpg'); ?>' alt="error"
            title="Aventura" ">
    </a>

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/livros/id/28/">
        <img class="books" src='<?php echo $this->getViewFileUrl('images/livro_romance.jpg'); ?>' alt="error"
            title="Romance" ">
    </a>

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/livros/id/30/">
        <img class="books" src='<?php echo $this->getViewFileUrl('images/livro_terror.jpg'); ?>' alt="error"
            title="Terror" ">
    </a>
</div>

<div><br/></div>

<div id="e_books">
    <h2><b>&nbsp;&nbsp;eBooks</b></h2>
    <img class="catalogo" src='<?php echo $this->getViewFileUrl('images/E-book.jpg'); ?>' alt="error" ">

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/e-books/id/25/">
        <img class="ebooks" src='<?php echo $this->getViewFileUrl('images/ebook_acao.jpg'); ?>' alt="error"
             title="Ação" ">
    </a>

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/e-books/id/27/">
        <img class="ebooks" src='<?php echo $this->getViewFileUrl('images/ebook_aventura.png'); ?>' alt="error"
             title="Aventura" ">
    </a>

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/e-books/id/29/">
        <img class="ebooks" src='<?php echo $this->getViewFileUrl('images/ebook_romance.png'); ?>' alt="error"
             title="Romance" ">
    </a>

    <a href="http://jumpers.develop/index.php/catalog/category/view/s/e-books/id/31/">
        <img class="ebooks" src='<?php echo $this->getViewFileUrl('images/ebook_terror.jpg'); ?>' alt="error"
             title="Terror" ">
    </a>
</div>

<div><br/></div>

<div id="banner02">
    <img src='<?php echo $this->getViewFileUrl('images/Banne2.jpg'); ?>' alt="error" ">
</div>