<div id="banner01">
    <a href="http://jumpers.develop/catalog/category/view/s/samsung/id/9/">
        <img src='<?php echo $this->getViewFileUrl('images/celular_samsung.png'); ?>' alt="error" ">
    </a>
</div>

<div><br/><br/></div>

<h2>
<b>Produtos</b>
</h2>

<div id="produtos">

    <a href="http://jumpers.develop/catalog/category/view/s/notebooks/id/5/">
        <img src='<?php echo $this->getViewFileUrl('images/notebooks.png'); ?>' alt="error" width="180" height="180"
        title="Notebook's" ">
    </a>

    <a href="http://jumpers.develop/catalog/category/view/s/smartphones/id/4/">
        <img src='<?php echo $this->getViewFileUrl('images/smartphones.png'); ?>' alt="error" width="180" height="180"
        title="Smartphones" ">
    </a>

    <a href="http://jumpers.develop/catalog/category/view/s/headset/id/16/">
        <img src='<?php echo $this->getViewFileUrl('images/headset.png'); ?>' alt="error" width="180" height="180"
        title="Headset" ">
    </a>

    <a href="http://jumpers.develop/catalog/category/view/s/mouse/id/17/">
        <img src='<?php echo $this->getViewFileUrl('images/mouse.png/'); ?>' alt="error" width="180" height="180"
        title="Mouse" ">
    </a>

    <a href="http://jumpers.develop/catalog/category/view/s/teclado/id/18/">
        <img src='<?php echo $this->getViewFileUrl('images/teclado.png/'); ?>' alt="error" width="200" height="185"
        title="Teclado" ">
    </a>

    <a href="http://jumpers.develop/catalog/category/view/s/consoles/id/6/">
        <img src='<?php echo $this->getViewFileUrl('images/consoles.png/'); ?>' alt="error" width="190" height="150"
        title="Consoles" ">
    </a>
</div>

<div id="banner02">

    <a href="http://jumpers.develop/catalog/category/view/s/notebooks/id/5/">
        <img src='<?php echo $this->getViewFileUrl('images/notebooks_categoria.png'); ?>' alt="error" ">
    </a>
</div>


